baseURL = "https://mazhe.pub/"
languageCode = "zh-CN"
title = "码者"
theme = "hugo-book"
enableRobotsTXT = true
buildDrafts = false

[params]
  BookTheme = "light"
  BookToC = true
  BookSearch = true
  BookMenuBundle = false
  BookSection = "docs"
  BookDateFormat = "2006-01-02"
  BookDescription = "开发者的效率工具"

[menu]
  [[menu.after]]
    name = "关于"
    url = "/about/"
    weight = 10

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true
